/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.omegat.gui.exttrans;

import javax.swing.JPanel;
import org.omegat.util.Preferences;
/**
 *
 * @author miurahr
 */
public class MicrosoftTranslateOptions extends javax.swing.JPanel {
    protected static final String OPTION_MICROSOFT_CLIENT_ID = "mt_microsoft_client_id";
    protected static final String OPTION_MICROSOFT_CLIENT_SECRET = "mt_microsoft_client_secret";
    
    private String userId;
    private String secret;
    
    
    /**
     * Creates new form MicrosoftTranslateOps
     */
    public MicrosoftTranslateOptions() {
        initComponents();
        userId = Preferences.getPreference(OPTION_MICROSOFT_CLIENT_ID);
        secret = Preferences.getPreference(OPTION_MICROSOFT_CLIENT_SECRET);
        setData();
    }

    public void update() {
	getData();
	Preferences.setPreference(OPTION_MICROSOFT_CLIENT_ID, userId);
	Preferences.setPreference(OPTION_MICROSOFT_CLIENT_SECRET, secret);
	Preferences.save();
    }

    public void setData() {
        userIdTextField.setText(userId);
        secretTextField.setText(secret);
    }

    public void getData() {
        userId = userIdTextField.getText();
        secret = secretTextField.getText();
    }

    public boolean isModified() {
        if (userIdTextField.getText() != null ? !userIdTextField.getText().equals(userId) : userId != null)
            return true;
        if (secretTextField.getText() != null ? !secretTextField.getText().equals(secret) :
                secret != null)
            return true;
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                userIdLabel = new javax.swing.JLabel();
                secretLabel = new javax.swing.JLabel();
                userIdTextField = new javax.swing.JTextField();
                secretTextField = new javax.swing.JTextField();

                userIdLabel.setText("User ID");
                userIdLabel.setToolTipText("");

                secretLabel.setText("Secret");

                userIdTextField.setText("user ID");

                secretTextField.setText("secret");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(userIdLabel)
                                        .addComponent(secretLabel))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(userIdTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                        .addComponent(secretTextField))
                                .addContainerGap(41, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(userIdLabel)
                                        .addComponent(userIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(secretLabel))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(secretTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(212, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel secretLabel;
        private javax.swing.JTextField secretTextField;
        private javax.swing.JLabel userIdLabel;
        private javax.swing.JTextField userIdTextField;
        // End of variables declaration//GEN-END:variables
}
