name: Run checkstyle

on: pull_request

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: run checkstyle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: checkstyleMain checkstyleTest
    - name: Publish Checkstyle report
      uses: Juuxel/publish-checkstyle-report@v1
      if: ${{ failure() || success() }}
      with:
        reports: |
          build/reports/checkstyle/*.xml
          tipoftheday/build/reports/checkstyle/*.xml
          machinetranslators/*/build/reports/checkstyle/*.xml
