name: Validate gradle wrapper

on:
  pull_request:

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: gradle/actions/wrapper-validation@v3
      name: validate gradle wrapper
