name: Lizard Cyclomatic Complexity Check

on:
  pull_request:
    paths:
      - '**/*.java'
  push:
    branches: ['main']
    paths:
      - '**/*.java'
      - '.github/workflows/lizard.yml'

jobs:
  lizard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Lizard
        run: |
          python -m pip install --upgrade pip
          pip install lizard
      - name: Run Lizard
        run: |
          lizard -C 10 -l java -f json -o lizard_output.json || true
      - name: Create GitHub annotations for Lizard results
        run: |
          # Parse JSON output and create annotations
          jq -r '.[] | select(.complexity > 10) | .file, .line, .complexity, .function' lizard_output.json | while read -r file line complexity function; do
            echo "::warning file=$file,line=$line::Function $function has cyclomatic complexity of $complexity (threshold 10)"
          done
